import assert from 'node:assert/strict'
import {mkdir,writeFile} from 'node:fs/promises'
import {join} from 'node:path'
import {spawnSync} from 'node:child_process'
export async function motionCheck({page,app,setup,readySelection=false}) {
  const out=join(setup.root,'visible-motion'),frames=join(out,'frames');await mkdir(frames,{recursive:true});const cdp=await page.context().newCDPSession(page),times=[],writes=[],rows=[]
  await page.bringToFront()
  cdp.on('Page.screencastFrame',e=>{const name=`frame-${String(times.length+1).padStart(5,'0')}.jpg`;times.push({name,time:e.metadata.timestamp});writes.push(writeFile(join(frames,name),Buffer.from(e.data,'base64')));cdp.send('Page.screencastFrameAck',{sessionId:e.sessionId}).catch(()=>{})});await cdp.send('Page.startScreencast',{format:'jpeg',quality:75,maxWidth:1500,maxHeight:960})
  const a=page.locator('.sf-source-input'),original=await a.inputValue()
  await page.evaluate(()=>{const original=window.fetch;window.__sfMotion={original,count:0,fail:false};window.fetch=async(input,init)=>{if(String(input).endsWith('api/scholarflow.v1/cowrite.propose')){const holder=window.__sfMotion,m=JSON.parse(init.body),r=m.payload.args.request;holder.count++;await new Promise(resolve=>setTimeout(resolve,1300));return new Response(JSON.stringify({type:'server-response',rpcId:m.rpcId,result:{ok:true,value:holder.fail?{ok:false,error:{code:'TRANSPORT',message:'TEST_ONLY 连接失败模拟；正文未改变。',details:{category:'provider/transport'}}}:{ok:true,data:{suggestion:{id:'cowrite_TEST_ONLY_motion',after:'TEST_ONLY 响应模拟：'+r.text.slice(r.start,r.end),citationChanges:{added:[],removed:[]},protectedFactChanges:[]}}}}}),{headers:{'content-type':'application/json'}})}return Reflect.apply(original,window,[input,init])}})
  try {
    if(!readySelection){await a.evaluate(e=>{const start=e.value.indexOf('\n\n',e.value.indexOf('## '))+2,end=e.value.indexOf('\n\n',start);e.focus();e.setSelectionRange(start,end)});await page.waitForTimeout(250);await a.dispatchEvent('mouseup')}await page.getByRole('button',{name:'润色',exact:true}).click();const input=page.getByRole('textbox',{name:'局部修改要求'})
    await input.focus();await cdp.send('Input.imeSetComposition',{text:'拼音组合',selectionStart:4,selectionEnd:4});await cdp.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:229});assert.equal(await page.evaluate(()=>window.__sfMotion.count),0);await cdp.send('Input.insertText',{text:'拼音组合'});rows.push({case:'IME',input:'CDP native composition',requests:0})
    await input.fill('TEST_ONLY 连续交互模拟');await input.press('Enter');await page.locator('.sf-rewrite[data-state=generating]').waitFor();assert.equal(await page.locator('.sf-rewrite-sweep').evaluate(e=>getComputedStyle(e,'::before').animationPlayState),'running');await page.locator('.sf-rewrite[data-state=ready]').waitFor();await page.getByRole('button',{name:'√ 采用',exact:true}).click();await page.getByRole('button',{name:'撤销接受',exact:true}).click();assert.equal(await a.inputValue(),original);await page.getByRole('button',{name:'× 放弃',exact:true}).click();rows.push({case:'visible input→generate→accept→undo→discard',type:'actual Electron with labeled response fixture',bodyExact:true})
    await page.waitForFunction(()=>!document.querySelector('.sf-source-input').disabled);await a.press('Control+Home')
    await a.evaluate(e=>{const start=e.value.indexOf('\n\n',e.value.indexOf('## '))+2,end=e.value.indexOf('\n\n',start);e.focus();e.setSelectionRange(start,end)});await a.dispatchEvent('mouseup');await page.getByRole('button',{name:'润色',exact:true}).click();await input.fill('TEST_ONLY 恢复草稿');for(let i=0;i<6;i++){await input.press('Escape');await page.getByRole('button',{name:'恢复修改输入'}).click()};assert.equal(await input.inputValue(),'TEST_ONLY 恢复草稿')
    await page.evaluate(()=>window.__sfMotion.fail=true);await input.press('Enter');await page.locator('.sf-rewrite[data-state=failed]').waitFor();assert.equal(await page.locator('.sf-rewrite-diff').count(),0);await page.getByRole('button',{name:'× 放弃',exact:true}).click();rows.push({case:'six collapse/restore + failure',noFakeDiff:true})
    await page.emulateMedia({reducedMotion:'reduce'});await page.screenshot({path:join(out,'reduced.png')});await page.emulateMedia({reducedMotion:'no-preference'});await page.screenshot({path:join(out,'final.png')})
  }finally{await page.evaluate(()=>{window.fetch=window.__sfMotion.original;delete window.__sfMotion});await cdp.send('Page.stopScreencast');await Promise.all(writes);await a.fill(original);await writeFile(join(out,'operations.json'),JSON.stringify({rows,frames:times.length},null,2));const concat=times.map((f,i)=>`file '${f.name}'\nduration ${Math.min(2,Math.max(.04,(times[i+1]?.time??f.time+.4)-f.time))}`).join('\n')+`\nfile '${times.at(-1).name}'\n`;await writeFile(join(frames,'frames.txt'),concat);const encoded=spawnSync('ffmpeg',['-y','-f','concat','-safe','0','-i',join(frames,'frames.txt'),'-vf','pad=ceil(iw/2)*2:ceil(ih/2)*2','-c:v','libx264','-pix_fmt','yuv420p',join(out,'interaction.mp4')],{windowsHide:true,stdio:'ignore'});await writeFile(join(out,'video-status.json'),JSON.stringify({status:encoded.status}));}
  return {out,rows}
}
