// TEST_ONLY deterministic model adapter. These are domain contract tests, not
// claims that their outputs were generated by a real provider.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { MemoryStore } from '../fixtures/memory-store.ts'
import { initialize, prepareInit, snapshot } from '../../src/core/project/project.ts'
import { saveManual } from '../../src/core/editing/proposals.ts'
import { prepareGeneration, executeGeneration } from '../../src/core/pipeline/generation.ts'
import { projectMarkdown } from '../../src/core/editing/markdown.ts'
const owner = { pid: 12345, bootInstance: 'TEST_ONLY' }

async function setup() {
  const io = new MemoryStore()
  await initialize(io, await prepareInit(io, { title: 'TEST_ONLY 有限阶段', type: 'course-paper' }))
  let current = await snapshot(io)
  await saveManual(io, 'TEST_ONLY 可改写的原文。', current.document.contentHash, 0)
  current = await snapshot(io)
  const block = projectMarkdown(current.document.text).blocks[0]
  const plan = await prepareGeneration(io, { context: { requestId: 'req_TEST_ONLY', workspaceId: 'ws_TEST_ONLY', sessionId: 'ses_TEST_ONLY', projectId: current.config.project.id, expectedLedgerRevision: current.ledger.revision },
    instruction: 'TEST_ONLY 只改善表达', selection: { projectId: current.config.project.id, documentId: 'paper', documentHash: current.document.contentHash, revisionId: current.document.revisionId,
      blockIds: [block.id], sourceRange: { startUtf16: block.start, endUtf16: block.end }, sourceText: current.document.text, renderedText: current.document.text,
      prefixContext: '', suffixContext: '', citationKeys: [], claimIds: [], scope: 'paragraph', capturedAt: new Date().toISOString() } }, { providerId: 'TEST_ONLY-provider', modelId: 'TEST_ONLY-model' })
  return { io, plan }
}
test('finite stage performs one structured-format repair, persists a proposal, and never applies it', async () => {
  const { io, plan } = await setup(), original = (await snapshot(io)).document.text
  let calls = 0, locked = false
  const lock = io.lock.bind(io); io.lock = fn => lock(async () => { locked = true; try { return await fn() } finally { locked = false } })
  const result = await executeGeneration(io, plan, owner, new AbortController().signal, async request => {
    assert.equal(locked, false, 'model calls must never occur under the project writer lock')
    calls++; if (calls === 1) return 'TEST_ONLY invalid JSON'
    assert.ok(request.repair)
    return JSON.stringify({ replacementText: 'TEST_ONLY 改善后的表达。', limitations: ['TEST_ONLY 语义仍需人工核对'] })
  }, () => true)
  assert.equal(calls, 2)
  assert.equal(result.run.status, 'completed-with-issues')
  assert.equal(result.run.usedModelCalls, 2)
  assert.equal((await snapshot(io)).document.text, original)
  assert.equal((await snapshot(io)).ledger.proposalStates[result.proposal.id].state, 'pending')
  assert.ok((await io.read(`.scholarflow/runs/${plan.snapshot.runId}/snapshot.json`))!.text.includes('TEST_ONLY-provider'))
})

test('invalid structured output fails after one repair without guessing an executable patch', async () => {
  const { io, plan } = await setup(), original = (await snapshot(io)).document.text
  let calls = 0
  await assert.rejects(executeGeneration(io, plan, owner, new AbortController().signal, async () => { calls++; return '```json\nnot executable\n```' }, () => true), { code: 'MODEL_OUTPUT_INVALID' })
  assert.equal(calls, 2); assert.equal((await snapshot(io)).document.text, original)
  assert.equal(JSON.parse((await io.read(`.scholarflow/runs/${plan.snapshot.runId}/state.json`))!.text).status, 'failed')
})

test('AT-24: only one modifying pipeline per project may execute', async () => {
  const { io, plan } = await setup()
  let entered!: () => void, release!: () => void
  const ready = new Promise<void>(resolve => { entered = resolve }), pending = new Promise<void>(resolve => { release = resolve })
  const first = executeGeneration(io, plan, owner, new AbortController().signal, async () => { entered(); await pending; return JSON.stringify({ replacementText: 'TEST_ONLY 新表达。', limitations: [] }) }, () => true)
  await ready
  await assert.rejects(executeGeneration(io, plan, owner, new AbortController().signal, async () => { throw new Error('must never be called') }, () => true), { code: 'RUN_IN_PROGRESS' })
  release(); await first
})

test('cancellation persists a terminal checkpoint and leaves the manuscript unchanged', async () => {
  const { io, plan } = await setup(), original = (await snapshot(io)).document.text, cancel = new AbortController()
  await assert.rejects(executeGeneration(io, plan, owner, cancel.signal, async request => {
    cancel.abort('user-cancel'); request.signal.throwIfAborted(); return ''
  }, () => true), { code: 'CANCELLED' })
  assert.equal((await snapshot(io)).document.text, original)
  assert.equal(JSON.parse((await io.read(`.scholarflow/runs/${plan.snapshot.runId}/state.json`))!.text).status, 'cancelled')
})

test('external Profile edits invalidate an approved plan before any model call', async () => {
  const { io, plan } = await setup(); let calls = 0
  io.externalEdit('.scholarflow/profiles/writing.md', 'TEST_ONLY 用户外部修改了文风')
  await assert.rejects(executeGeneration(io, plan, owner, new AbortController().signal, async () => { calls++; return '' }, () => true), { code: 'STALE_RESOURCE_VERSION' })
  assert.equal(calls, 0)
})
