// TEST_ONLY deterministic model adapter. These are domain contract tests, not
// claims that their outputs were generated by a real provider.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { MemoryStore } from '../fixtures/memory-store.ts'
import { proposalOf, proposalHashOf } from '../fixtures/generation-result.ts'
import { initialize, prepareInit, snapshot } from '../../src/core/project/project.ts'
import { saveManual, applyProposal } from '../../src/core/editing/proposals.ts'
import { prepareGeneration, executeGeneration, validateModelReplacement } from '../../src/core/pipeline/generation.ts'
import { projectMarkdown } from '../../src/core/editing/markdown.ts'
import { prepareRunAction, closeRun } from '../../src/core/pipeline/run-control.ts'
import { readRun, runFile, ACTIVE_RUN } from '../../src/core/pipeline/run-store.ts'
import { json, digest } from '../../src/core/store/files.ts'
import { ScholarError } from '../../src/shared/errors.ts'
const owner = { pid: 12345, bootInstance: 'TEST_ONLY' }

async function setup() {
  const io = new MemoryStore()
  await initialize(io, await prepareInit(io, { title: 'TEST_ONLY 有限阶段', type: 'course-paper' }))
  let current = await snapshot(io)
  await saveManual(io, 'TEST_ONLY 可改写的原文。', current.document.contentHash, 0)
  current = await snapshot(io)
  const block = projectMarkdown(current.document.text).blocks[0]
  const plan = await prepareGeneration(io, { context: { requestId: 'req_TEST_ONLY', workspaceId: 'ws_TEST_ONLY', sessionId: 'ses_TEST_ONLY', projectId: current.config.project.id, expectedLedgerRevision: current.ledger.revision },
    instruction: 'TEST_ONLY 只改善表达', selection: { projectId: current.config.project.id, documentId: 'paper', documentHash: current.document.contentHash, revisionId: current.document.revisionId,
      blockIds: [block.id], sourceRange: { startUtf16: block.start, endUtf16: block.end }, sourceText: current.document.text, renderedText: current.document.text,
      prefixContext: '', suffixContext: '', citationKeys: [], claimIds: [], scope: 'paragraph', capturedAt: new Date().toISOString() } }, { providerId: 'TEST_ONLY-provider', modelId: 'TEST_ONLY-model' })
  return { io, plan }
}
test('finite stage performs one structured-format repair, persists a proposal, and never applies it', async () => {
  const { io, plan } = await setup(), original = (await snapshot(io)).document.text
  let calls = 0, locked = false
  const lock = io.lock.bind(io); io.lock = fn => lock(async () => { locked = true; try { return await fn() } finally { locked = false } })
  const result = await executeGeneration(io, plan, owner, new AbortController().signal, async request => {
    assert.equal(locked, false, 'model calls must never occur under the project writer lock')
    calls++; if (calls === 1) return 'TEST_ONLY invalid JSON'
    assert.ok(request.repair)
    return JSON.stringify({ replacementText: 'TEST_ONLY 改善后的表达。', limitations: ['TEST_ONLY 语义仍需人工核对'] })
  }, () => true)
  assert.equal(calls, 2)
  assert.equal(result.run.status, 'completed-with-issues')
  assert.equal(result.run.usedModelCalls, 2)
  assert.equal((await snapshot(io)).document.text, original)
  assert.equal((await snapshot(io)).ledger.proposalStates[proposalOf(result).id].state, 'pending')
  assert.ok((await io.read(`.scholarflow/runs/${plan.snapshot.runId}/input.json`))!.text.includes('TEST_ONLY-provider'))
})

test('invalid structured output fails after one repair without guessing an executable patch', async () => {
  const { io, plan } = await setup(), original = (await snapshot(io)).document.text
  let calls = 0
  await assert.rejects(executeGeneration(io, plan, owner, new AbortController().signal, async () => { calls++; return '```json\nnot executable\n```' }, () => true), { code: 'MODEL_OUTPUT_INVALID' })
  assert.equal(calls, 2); assert.equal((await snapshot(io)).document.text, original)
  assert.equal(JSON.parse((await io.read(`.scholarflow/runs/${plan.snapshot.runId}/run.json`))!.text).status, 'failed')
})

test('AT-24: only one modifying pipeline per project may execute', async () => {
  const { io, plan } = await setup()
  let entered!: () => void, release!: () => void
  const ready = new Promise<void>(resolve => { entered = resolve }), pending = new Promise<void>(resolve => { release = resolve })
  const first = executeGeneration(io, plan, owner, new AbortController().signal, async () => { entered(); await pending; return JSON.stringify({ replacementText: 'TEST_ONLY 新表达。', limitations: [] }) }, () => true)
  await ready
  await assert.rejects(executeGeneration(io, plan, owner, new AbortController().signal, async () => { throw new Error('must never be called') }, () => true), { code: 'RUN_IN_PROGRESS' })
  release(); await first
})

test('cancellation persists a terminal checkpoint and leaves the manuscript unchanged', async () => {
  const { io, plan } = await setup(), original = (await snapshot(io)).document.text, cancel = new AbortController()
  await assert.rejects(executeGeneration(io, plan, owner, cancel.signal, async request => {
    cancel.abort('user-cancel'); request.signal.throwIfAborted(); return ''
  }, () => true), { code: 'CANCELLED' })
  assert.equal((await snapshot(io)).document.text, original)
  assert.equal(JSON.parse((await io.read(`.scholarflow/runs/${plan.snapshot.runId}/run.json`))!.text).status, 'cancelled')
})

test('external Profile edits invalidate an approved plan before any model call', async () => {
  const { io, plan } = await setup(); let calls = 0
  io.externalEdit('.scholarflow/profiles/writing.md', 'TEST_ONLY 用户外部修改了文风')
  await assert.rejects(executeGeneration(io, plan, owner, new AbortController().signal, async () => { calls++; return '' }, () => true), { code: 'STALE_RESOURCE_VERSION' })
  assert.equal(calls, 0)
})

test('valid JSON with invented selection citations still fails after one repair without a proposal', async () => {
  const { io, plan } = await setup(); let calls = 0
  await assert.rejects(executeGeneration(io, plan, owner, new AbortController().signal, async () => {
    calls++; return JSON.stringify({ replacementText: 'TEST_ONLY [@sf_not_in_input]', limitations: [] })
  }, () => true), { code: 'MODEL_OUTPUT_INVALID' })
  assert.equal(calls, 2); assert.equal(Object.keys((await snapshot(io)).ledger.proposalStates).length, 0)
})

test('whole-document writer must return parsed evidence citations, not bare or parenthesized keys', async () => {
  const { plan } = await setup()
  const whole = { ...plan, input: { ...plan.input, selection: undefined }, context: { ...plan.context, sources: [{ citeKey: 'sf_TEST_ONLY' }] } }
  for (const text of ['TEST_ONLY 无引用。', 'TEST_ONLY (sf_TEST_ONLY)。', 'TEST_ONLY sf_TEST_ONLY。', 'TEST_ONLY `[@sf_TEST_ONLY]`。'])
    assert.throws(() => validateModelReplacement(whole, text), { code: 'MODEL_CITATION_INVALID' })
  validateModelReplacement(whole, 'TEST_ONLY 有效引用 [@sf_TEST_ONLY]。')
})

test('a section and a rendered selection cannot be combined into an ambiguous scope', async () => {
  const { io, plan } = await setup()
  await assert.rejects(prepareGeneration(io, { ...plan.input, sectionId: 'sec_TEST_ONLY' }, plan.snapshot.modelDescriptor), { name: 'ZodError' })
  assert.equal((await snapshot(io)).document.text, plan.input.selection!.sourceText)
})

test('external run-state edits cannot be overwritten by a refreshed persistence preimage', async () => {
  const { io, plan } = await setup(), original = (await snapshot(io)).document.text
  const path = `.scholarflow/runs/${plan.snapshot.runId}/run.json`
  await assert.rejects(executeGeneration(io, plan, owner, new AbortController().signal, async () => {
    const state = JSON.parse((await io.read(path))!.text)
    io.externalEdit(path, JSON.stringify({ ...state, status: 'paused', errorCode: 'TEST_ONLY_EXTERNAL' }))
    return 'TEST_ONLY invalid output to trigger the next checkpoint'
  }, () => true), { code: 'RUN_STATE_CHANGED' })
  assert.equal(JSON.parse((await io.read(path))!.text).errorCode, 'TEST_ONLY_EXTERNAL')
  assert.equal((await snapshot(io)).document.text, original)
})

test('pause stops dispatch, persists frozen inputs, and resumes after explicit unchanged-input confirmation', async () => {
  const { io, plan } = await setup(), original = (await snapshot(io)).document.text
  const paused = await executeGeneration(io, plan, owner, new AbortController().signal, async () => { throw new Error('paused must not dispatch') }, () => true,
    { pauseRequested: () => true })
  assert.equal(paused.run.status, 'paused'); assert.equal(paused.run.usedModelCalls, 0)
  const writes = io.writes, preview = await prepareRunAction(io, plan.snapshot.runId, 'resume', () => true)
  assert.equal(io.writes, writes, 'preview must be read-only')
  const resumed = await executeGeneration(io, preview.frozen!, { pid: 9999, bootInstance: 'TEST_ONLY_new' }, new AbortController().signal,
    async () => JSON.stringify({ replacementText: 'TEST_ONLY 明确恢复的新候选。', limitations: [] }), () => true,
    { resume: preview, pauseRequested: () => false, executionSessionId: 'ses_TEST_ONLY_second' })
  assert.equal(resumed.run.usedModelCalls, 1); assert.equal(resumed.run.sessionId, plan.snapshot.sessionId)
  assert.equal(resumed.run.executionSessionId, 'ses_TEST_ONLY_second')
  assert.equal((await snapshot(io)).document.text, original)
  assert.equal(resumed.run.status, 'completed-with-issues')
})

test('a paused format repair resumes only the remaining attempt and never renews its budget', async () => {
  const { io, plan } = await setup(); let requested = false, calls = 0
  const paused = await executeGeneration(io, plan, owner, new AbortController().signal, async () => { calls++; requested = true; return 'TEST_ONLY invalid JSON' }, () => true,
    { pauseRequested: () => requested })
  assert.equal(paused.run.status, 'paused'); assert.equal(calls, 1)
  const preview = await prepareRunAction(io, plan.snapshot.runId, 'resume', () => true)
  await assert.rejects(executeGeneration(io, preview.frozen!, owner, new AbortController().signal, async request => {
    assert.ok(request.repair); calls++; return 'TEST_ONLY still invalid'
  }, () => true, { resume: preview, pauseRequested: () => false }), { code: 'MODEL_OUTPUT_INVALID' })
  assert.equal(calls, 2)
  assert.equal((await readRun(io, plan.snapshot.runId, plan.snapshot.projectId)).run.usedModelCalls, 2)
})

test('validated output checkpoint is reused without a second paid call after pause', async () => {
  const { io, plan } = await setup(); let requested = false
  const paused = await executeGeneration(io, plan, owner, new AbortController().signal, async () => {
    requested = true; return JSON.stringify({ replacementText: 'TEST_ONLY 已保存的有效候选。', limitations: ['TEST_ONLY'] })
  }, () => true, { pauseRequested: () => requested })
  assert.equal(paused.run.status, 'paused'); assert.equal(Object.keys((await snapshot(io)).ledger.proposalStates).length, 0)
  const preview = await prepareRunAction(io, plan.snapshot.runId, 'resume', () => true)
  const resumed = await executeGeneration(io, preview.frozen!, owner, new AbortController().signal, async () => { throw new Error('must reuse validated candidate') },
    () => true, { resume: preview, pauseRequested: () => false })
  assert.equal(proposalOf(resumed).edits[0].replacementText, 'TEST_ONLY 已保存的有效候选。')
  assert.equal(resumed.run.usedModelCalls, 1)
})

test('dead-owner recovery charges unanswered calls and never steals a live process', async () => {
  const { io, plan } = await setup(); let crashed!: MemoryStore
  await executeGeneration(io, plan, owner, new AbortController().signal, async () => {
    // TEST_ONLY process image captured after call charge, before its response.
    crashed = new MemoryStore(Object.fromEntries([...io.files].map(([path, image]) => [path, image.text])))
    return JSON.stringify({ replacementText: 'TEST_ONLY old process candidate.', limitations: [] })
  }, () => true)
  const writes = crashed.writes
  await assert.rejects(prepareRunAction(crashed, plan.snapshot.runId, 'resume', () => true), { code: 'RUN_OWNER_ALIVE' })
  assert.equal(crashed.writes, writes)
  const preview = await prepareRunAction(crashed, plan.snapshot.runId, 'resume', () => false)
  const resumed = await executeGeneration(crashed, preview.frozen!, { pid: 23456, bootInstance: 'TEST_ONLY_restart' }, new AbortController().signal,
    async () => JSON.stringify({ replacementText: 'TEST_ONLY 明确恢复后的结果。', limitations: [] }), () => false,
    { resume: preview, pauseRequested: () => false })
  assert.equal(resumed.run.usedModelCalls, 2)
  assert.equal(Object.keys((await snapshot(crashed)).ledger.proposalStates).length, 1)
})

test('recovery of an already accepted proposal cannot repeat model calls or accepted manuscript edits', async () => {
  const { io, plan } = await setup()
  const result = await executeGeneration(io, plan, owner, new AbortController().signal,
    async () => JSON.stringify({ replacementText: 'TEST_ONLY 已接受的用户稿。', limitations: [] }), () => true)
  assert.ok(proposalOf(result))
  const current = await snapshot(io)
  await applyProposal(io, proposalOf(result).id, current.ledger.revision, proposalHashOf(result))
  // TEST_ONLY fault image: proposal published, terminal state not yet saved.
  const stored = await readRun(io, plan.snapshot.runId, plan.snapshot.projectId)
  const interrupted = json({ ...stored.run, status: 'running', proposalId: undefined })
  io.externalEdit(runFile(plan.snapshot.runId), interrupted); io.externalEdit(ACTIVE_RUN, interrupted)
  const before = await snapshot(io), preview = await prepareRunAction(io, plan.snapshot.runId, 'resume', () => false)
  assert.equal(preview.existingProposalState, 'accepted')
  const recovered = await executeGeneration(io, preview.frozen!, { pid: 23456, bootInstance: 'TEST_ONLY_restart' }, new AbortController().signal,
    async () => { throw new Error('accepted proposal must never regenerate') }, () => false, { resume: preview, pauseRequested: () => false })
  assert.equal(recovered.run.proposalId, proposalOf(result).id); assert.equal(recovered.run.status, 'completed-with-issues')
  const after = await snapshot(io)
  assert.equal(after.ledgerHash, before.ledgerHash); assert.equal(after.document.text, before.document.text)
  await assert.rejects(prepareRunAction(io, plan.snapshot.runId, 'resume', () => false), { code: 'RUN_TERMINAL' })
})

test('resume confirmation rejects changed inputs and close preserves them while releasing the old run', async () => {
  const { io, plan } = await setup()
  await executeGeneration(io, plan, owner, new AbortController().signal, async () => '', () => true, { pauseRequested: () => true })
  const preview = await prepareRunAction(io, plan.snapshot.runId, 'resume', () => true)
  io.externalEdit('.scholarflow/profiles/writing.md', 'TEST_ONLY 外部文风变更')
  await assert.rejects(executeGeneration(io, preview.frozen!, owner, new AbortController().signal, async () => { throw new Error('must not dispatch') },
    () => true, { resume: preview, pauseRequested: () => false }), { code: 'STALE_RESOURCE_VERSION' })
  const original = (await snapshot(io)).document.text, close = await prepareRunAction(io, plan.snapshot.runId, 'close', () => true)
  await closeRun(io, close, () => true)
  assert.equal((await snapshot(io)).document.text, original)
  assert.equal((await io.read('.scholarflow/profiles/writing.md'))!.text, 'TEST_ONLY 外部文风变更')
  assert.equal((await readRun(io, plan.snapshot.runId, plan.snapshot.projectId)).run.status, 'cancelled')
  assert.equal((await readRun(io, plan.snapshot.runId, plan.snapshot.projectId)).run.usedModelCalls, 0)
})

test('failed-run retry creates linked new history rather than erasing the original terminal record', async () => {
  const { io, plan } = await setup()
  await assert.rejects(executeGeneration(io, plan, owner, new AbortController().signal, async () => { throw new Error('TEST_ONLY provider unavailable') }, () => true))
  const failed = (await io.read(runFile(plan.snapshot.runId)))!.text
  const preview = await prepareRunAction(io, plan.snapshot.runId, 'retry', () => false)
  const fresh = await prepareGeneration(io, preview.frozen!.input, plan.snapshot.modelDescriptor)
  const { contentHash: _hash, ...body } = fresh, linked = { ...body, parentRunId: plan.snapshot.runId }
  const result = await executeGeneration(io, { ...linked, contentHash: digest(json(linked)) }, owner, new AbortController().signal,
    async () => JSON.stringify({ replacementText: 'TEST_ONLY 用户明确重试。', limitations: [] }), () => true)
  assert.notEqual(result.run.runId, plan.snapshot.runId); assert.equal(result.run.parentRunId, plan.snapshot.runId)
  assert.equal((await io.read(runFile(plan.snapshot.runId)))!.text, failed)
  assert.equal(result.run.usedModelCalls, 1)
})

test('temporary errors stop after two retries, retain every charged call, and never invent a format result', async () => {
  const { io, plan } = await setup(); let calls = 0
  await assert.rejects(executeGeneration(io, plan, owner, new AbortController().signal, async () => {
    calls++; throw new ScholarError('SERVER', 'TEST_ONLY provider failure', { status: 503 })
  }, () => true), { code: 'SERVER' })
  const stored = await readRun(io, plan.snapshot.runId, plan.snapshot.projectId), checkpoint = JSON.parse((await io.read(`.scholarflow/runs/${stored.run.runId}/checkpoint.json`))!.text)
  assert.equal(calls, 3); assert.equal(stored.run.usedModelCalls, 3); assert.equal(stored.run.status, 'failed')
  assert.equal(checkpoint.transientRetries, 2); assert.equal(checkpoint.formatAttempts, 0)
  assert.equal(Object.keys((await snapshot(io)).ledger.proposalStates).length, 0)
})

test('authentication errors never auto-retry, while pause preserves a provider window across recovery', async () => {
  const auth = await setup(); let authCalls = 0
  await assert.rejects(executeGeneration(auth.io, auth.plan, owner, new AbortController().signal, async () => {
    authCalls++; throw new ScholarError('AUTH', 'TEST_ONLY invalid credential', { status: 401 })
  }, () => true), { code: 'AUTH' })
  assert.equal(authCalls, 1)
  const { io, plan } = await setup(); let pause = false
  const before = Date.now()
  const paused = await executeGeneration(io, plan, owner, new AbortController().signal, async () => {
    pause = true; throw new ScholarError('RATE_LIMIT', 'TEST_ONLY', { status: 429, providerRetryAfterMs: 120000 })
  }, () => true, { pauseRequested: () => pause })
  const preview = await prepareRunAction(io, plan.snapshot.runId, 'resume', () => true)
  assert.equal(paused.run.status, 'paused'); assert.ok(preview.retryNotBefore! >= before + 120000)
  let calls = 0
  const cancel = new AbortController()
  const resumed = executeGeneration(io, preview.frozen!, owner, cancel.signal, async () => { calls++; return '' }, () => true,
    { resume: preview, pauseRequested: () => false })
  // TEST_ONLY wait only for durable resume registration, then cancel its timer.
  while ((await readRun(io, plan.snapshot.runId, plan.snapshot.projectId)).run.status === 'paused') await new Promise(resolve => setTimeout(resolve, 5))
  cancel.abort('user-cancel')
  await assert.rejects(resumed, { code: 'CANCELLED' }); assert.equal(calls, 0)
  assert.equal((await readRun(io, plan.snapshot.runId, plan.snapshot.projectId)).run.usedModelCalls, 1)
})

test('project inputs are rechecked before a format repair or transient retry dispatch', async () => {
  const { io, plan } = await setup(); let calls = 0
  await assert.rejects(executeGeneration(io, plan, owner, new AbortController().signal, async () => {
    calls++; io.externalEdit('.scholarflow/profiles/writing.md', 'TEST_ONLY permissions and instruction inputs changed')
    return 'TEST_ONLY invalid JSON'
  }, () => true), { code: 'STALE_RESOURCE_VERSION' })
  assert.equal(calls, 1)
  assert.equal((await readRun(io, plan.snapshot.runId, plan.snapshot.projectId)).run.status, 'paused')
})
